// Blog
var blogCount;
var blogPanelToLoad;
var panelsPerSection;
var listView;
var listWrapper;
var postTitle;
var postDate;
var postView;
var postMDinject;
var loadMoreButton;
// Projects
var projectsJSON;
var projectsCount;
var projectsWrapper;
var projectToLoad;
var projectsPanelsPerSection;
var projectsLoadMoreButton;
var githubCardsScript;
